# Generated by Django 3.1.3 on 2020-11-27 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201127_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ask_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда задан вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.category', verbose_name='категория вопроса'),
        ),
    ]
