# Generated by Django 3.1.3 on 2020-11-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201128_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
    ]
