# Generated by Django 3.1.3 on 2020-11-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_request_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.TextField(blank=True, null=True, verbose_name='Статус'),
        ),
    ]
