# Generated by Django 3.1.3 on 2020-11-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201128_0259'),
        ('api', '0011_request_created_at'),
    ]

    operations = [
    ]
