# Generated by Django 3.1.3 on 2020-11-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_request_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='request',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Черновик?'),
        ),
    ]
