# Generated by Django 3.1.3 on 2020-11-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201128_0532'),
        ('api', '0014_auto_20201128_0654'),
    ]

    operations = [
    ]
