# Generated by Django 3.1.3 on 2020-11-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_request_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.TextField(blank=True, choices=[('draft', 'draft'), ('registration', 'registration'), ('on_approval', 'on_approval'), ('revision', 'revision')], default='draft', null=True, verbose_name='Статус'),
        ),
    ]
