# Generated by Django 3.1.3 on 2020-11-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201128_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.TextField(blank=True, choices=[('Черновик', 'draft'), ('Ожидает модерации', 'registration'), ('Ожидает подтверждения', 'on_approval'), ('Ожидает правок', 'revision')], default='draft', null=True, verbose_name='Статус'),
        ),
    ]
