# Generated by Django 3.1.3 on 2020-11-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201128_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.TextField(blank=True, choices=[('draft', 'Черновик'), ('registration', 'Ожидает модерации'), ('on_approval', 'Ожидает подтверждения'), ('revision', 'Ожидает правок')], default='draft', null=True, verbose_name='Статус'),
        ),
    ]
