# Generated by Django 3.1.3 on 2020-11-28 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20201128_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.TextField(verbose_name='Организация/отдел проверяющего')),
                ('email_text', models.TextField(blank=True, null=True, verbose_name='Текст письма')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт эксперта')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='experts',
            field=models.ManyToManyField(blank=True, to='api.Expert', verbose_name='Проверяющие'),
        ),
    ]
